#!/bin/bash

# 安全执行模式
set -eo pipefail

# 获取git仓库根目录
GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")

# 设置输出路径（可配置）
OUTPUT_DIR="${GIT_ROOT}/src/include"
mkdir -p "${OUTPUT_DIR}"

# 获取版本信息（带错误处理）
get_git_info() {
    # 获取完整提交ID
    COMMIT_ID=$(git rev-parse HEAD 2>/dev/null || echo "unknown_commit")

    # 获取最近标签（含轻量标签）
    TAG=$(git describe --tags --always 2>/dev/null || echo "no_tags")

    # 获取分支信息
    BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "detached_head")

    # 获取脏工作区状态
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
        DIRTY="-dirty"
    else
        DIRTY=""
    fi
}

# 生成头文件内容
generate_header() {
    cat <<EOF
#ifndef GIT_INFO_H
#define GIT_INFO_H

/* Auto-generated by build system - DO NOT EDIT */
#define GIT_COMMIT_ID      "${COMMIT_ID}${DIRTY}"
#define GIT_TAG            "${TAG}"
#define GIT_BRANCH         "${BRANCH}"
#define BUILD_TIMESTAMP    "${TIMESTAMP}"

#endif /* GIT_INFO_H */
EOF
}

# 主执行流程
main() {
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    get_git_info
    
    # 仅在git仓库中生成真实信息
    if [ -n "${GIT_ROOT}" ]; then
        generate_header > "${OUTPUT_DIR}/git_info.h"
    else
        # 非git环境生成默认值
        cat <<EOF > "${OUTPUT_DIR}/git_info.h"
#ifndef GIT_INFO_H
#define GIT_INFO_H

#define GIT_COMMIT_ID      "non_git_build"
#define GIT_TAG            "unknown"
#define GIT_BRANCH         "unknown"
#define BUILD_TIMESTAMP    "${TIMESTAMP}"

#endif
EOF
    fi
}

main