#ifndef GIT_INFO_H
#define GIT_INFO_H

/* Auto-generated by build system - DO NOT EDIT */
#define GIT_COMMIT_ID      "3d4c088b72e87fc8511aeff8cad216b104d3ccb9-dirty"
#define GIT_TAG            "3d4c088"
#define GIT_BRANCH         "test-reload-plugin"
#define BUILD_TIMESTAMP    "2025-05-27T07:59:21Z"

#endif /* GIT_INFO_H */
