#ifndef GIT_INFO_H
#define GIT_INFO_H

/* Auto-generated by build system - DO NOT EDIT */
#define GIT_COMMIT_ID      "262569c691084d3789137f45afd82188e5b02490-dirty"
#define GIT_TAG            "262569c"
#define GIT_BRANCH         "test-reload-plugin"
#define BUILD_TIMESTAMP    "2025-11-12T09:33:46Z"

#endif /* GIT_INFO_H */
