#ifndef GIT_INFO_H
#define GIT_INFO_H

/* Auto-generated by build system - DO NOT EDIT */
#define GIT_COMMIT_ID      "44772cae65b3ce889a58693ae3e3d75854c1299b"
#define GIT_TAG            "44772ca"
#define GIT_BRANCH         "test-reload-plugin"
#define BUILD_TIMESTAMP    "2025-11-18T09:53:25Z"

#endif /* GIT_INFO_H */
